/* eslint-disable */
/* prettier-ignore-start */
/* auto-generated by TanStack Router */
import { Route as rootRoute } from './routes/__root.js'
import { Route as AuthenticatedImport } from './routes/_authenticated.js'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated.dashboard.js'
import { Route as AuthenticatedVehiclesImport } from './routes/_authenticated.vehicles.js'
import { Route as AuthenticatedDriversImport } from './routes/_authenticated.drivers.js'
import { Route as AuthenticatedTripsImport } from './routes/_authenticated.trips.js'
import { Route as AuthenticatedMaintenanceImport } from './routes/_authenticated.maintenance.js'
import { Route as LoginImport } from './routes/login.js'
import { Route as IndexImport } from './routes/index.js'

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedVehiclesRoute = AuthenticatedVehiclesImport.update({
  id: '/_authenticated/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDriversRoute = AuthenticatedDriversImport.update({
  id: '/_authenticated/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTripsRoute = AuthenticatedTripsImport.update({
  id: '/_authenticated/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMaintenanceRoute = AuthenticatedMaintenanceImport.update({
  id: '/_authenticated/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/_authenticated': { id: '/_authenticated'; path: '/'; fullPath: '/'; preLoaderRoute: typeof AuthenticatedImport; parentRoute: typeof rootRoute }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginImport; parentRoute: typeof rootRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardImport; parentRoute: typeof AuthenticatedImport }
    '/_authenticated/vehicles': { id: '/_authenticated/vehicles'; path: '/vehicles'; fullPath: '/vehicles'; preLoaderRoute: typeof AuthenticatedVehiclesImport; parentRoute: typeof AuthenticatedImport }
    '/_authenticated/drivers': { id: '/_authenticated/drivers'; path: '/drivers'; fullPath: '/drivers'; preLoaderRoute: typeof AuthenticatedDriversImport; parentRoute: typeof AuthenticatedImport }
    '/_authenticated/trips': { id: '/_authenticated/trips'; path: '/trips'; fullPath: '/trips'; preLoaderRoute: typeof AuthenticatedTripsImport; parentRoute: typeof AuthenticatedImport }
    '/_authenticated/maintenance': { id: '/_authenticated/maintenance'; path: '/maintenance'; fullPath: '/maintenance'; preLoaderRoute: typeof AuthenticatedMaintenanceImport; parentRoute: typeof AuthenticatedImport }
  }
}

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedDashboardRoute,
    AuthenticatedVehiclesRoute,
    AuthenticatedDriversRoute,
    AuthenticatedTripsRoute,
    AuthenticatedMaintenanceRoute,
  }),
})

/* prettier-ignore-end */
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": { "filePath": "__root.tsx", "children": ["/", "/login", "/_authenticated"] },
    "/": { "filePath": "index.tsx" },
    "/login": { "filePath": "login.tsx" },
    "/_authenticated": { "filePath": "_authenticated.tsx", "children": ["/_authenticated/dashboard", "/_authenticated/vehicles", "/_authenticated/drivers", "/_authenticated/trips", "/_authenticated/maintenance"] },
    "/_authenticated/dashboard": { "filePath": "_authenticated.dashboard.tsx" },
    "/_authenticated/vehicles": { "filePath": "_authenticated.vehicles.tsx" },
    "/_authenticated/drivers": { "filePath": "_authenticated.drivers.tsx" },
    "/_authenticated/trips": { "filePath": "_authenticated.trips.tsx" },
    "/_authenticated/maintenance": { "filePath": "_authenticated.maintenance.tsx" }
  }
}
ROUTE_MANIFEST_END */
