/* eslint-disable */
/* prettier-ignore-start */
/* auto-generated by TanStack Router */
import { Route as rootRoute } from './routes/__root.js'
import { Route as LoginImport } from './routes/login.js'
import { Route as IndexImport } from './routes/index.js'

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
  }
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login'
  id: '__root__' | '/' | '/login'
  fileRoutesById: FileRoutesById
}

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
})

/* prettier-ignore-end */
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": { "filePath": "__root.tsx", "children": ["/", "/login"] },
    "/": { "filePath": "index.tsx" },
    "/login": { "filePath": "login.tsx" }
  }
}
ROUTE_MANIFEST_END */
